name: Swift Test

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/swift-test.yml'
      - '**.swift'
  pull_request:
    branches: [ "main" ]

jobs:
  SwiftTest:
    name: Swift Test on macOS 12
    runs-on: macos-12
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Setup swift
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5.9"
      - name: Run tests
        run: swift test --enable-code-coverage
      - name: Code coverage
        uses: maxep/spm-lcov-action@0.3.0
        with:
          file-format: text
          output-file: ./coverage/info.json
